language: csharp
solution: SocialNetwork.sln
mono: none
dotnet: 2.1.0
build: trusty
jobs:
  include:
    - stage: build
      script: ./scripts/linux/build.sh
    - stage: test
      script: ./scripts/linux/test.sh